export const TOOLS = [
  { category: 'SEO',    name: 'Meta tag generator',  description: 'Generate SEO meta tags with live preview',            route: '/meta-tags-generator'  },
  { category: 'SEO',    name: 'OG Image Generator', description: 'Crop and export Open Graph images at 1200×630',         route: '/og-image-generator'   },
  { category: 'Images', name: 'WebP converter',   description: 'Convert any image to WebP format',              route: '/webp-converter'  },
  { category: 'Images', name: 'Favicon generator', description: 'Generate favicons from text, emoji, or image', route: '/favicon-generator' },
  { category: 'Images', name: 'Compress JPG',      description: 'Reduce JPEG file size with quality control',    route: '/compress-jpg'    },
  { category: 'Images', name: 'Compress PNG',      description: 'Lossless PNG compression, strip metadata',      route: '/compress-png'    },
  { category: 'Images', name: 'Compress WebP',     description: 'Reduce WebP file size, adjustable quality',     route: '/compress-webp'   },
  { category: 'Images', name: 'PNG to JPG',        description: 'Convert PNG images to JPG',                     route: '/png-to-jpg'      },
  { category: 'Images', name: 'JPG to PNG',        description: 'Convert JPG images to PNG',                     route: '/jpg-to-png'      },
  { category: 'Images', name: 'WebP to JPG',       description: 'Convert WebP images to JPG',                    route: '/webp-to-jpg'     },
  { category: 'Images', name: 'WebP to PNG',       description: 'Convert WebP images to PNG',                    route: '/webp-to-png'     },
  { category: 'Images', name: 'PNG to WebP',       description: 'Convert PNG images to WebP',                    route: '/png-to-webp'     },
  { category: 'Images', name: 'JPG to WebP',       description: 'Convert JPG images to WebP',                    route: '/jpg-to-webp'     },
  { category: 'Images', name: 'JPEG to PNG',       description: 'Convert JPEG images to PNG',                    route: '/jpeg-to-png'     },
  { category: 'Images', name: 'JPEG to WebP',      description: 'Convert JPEG images to WebP',                   route: '/jpeg-to-webp'    },
  { category: 'Images', name: 'GIF to JPG',        description: 'Convert GIF images to JPG',                     route: '/gif-to-jpg'      },
  { category: 'Images', name: 'GIF to PNG',        description: 'Convert GIF images to PNG',                     route: '/gif-to-png'      },
  { category: 'Images', name: 'GIF to WebP',       description: 'Convert GIF images to WebP',                    route: '/gif-to-webp'     },
  { category: 'Images', name: 'BMP to JPG',        description: 'Convert BMP images to JPG',                     route: '/bmp-to-jpg'      },
  { category: 'Images', name: 'BMP to PNG',        description: 'Convert BMP images to PNG',                     route: '/bmp-to-png'      },
  { category: 'Images', name: 'BMP to WebP',       description: 'Convert BMP images to WebP',                    route: '/bmp-to-webp'     },
  { category: 'Images', name: 'AVIF to JPG',       description: 'Convert AVIF images to JPG',                    route: '/avif-to-jpg'     },
  { category: 'Images', name: 'AVIF to PNG',       description: 'Convert AVIF images to PNG',                    route: '/avif-to-png'     },
  { category: 'Images', name: 'AVIF to WebP',      description: 'Convert AVIF images to WebP',                   route: '/avif-to-webp'    },
  { category: 'Images', name: 'TIFF to JPG',       description: 'Convert TIFF images to JPG',                    route: '/tiff-to-jpg'     },
  { category: 'Images', name: 'TIFF to PNG',       description: 'Convert TIFF images to PNG',                    route: '/tiff-to-png'     },
  { category: 'Images', name: 'TIFF to WebP',      description: 'Convert TIFF images to WebP',                   route: '/tiff-to-webp'    },
]
