export const TOOLS = [
  { category: 'Text & Code', name: 'HTML to Markdown', description: 'Convert HTML to clean Markdown — browser-based, instant', route: '/html-to-markdown', lastmod: '2026-05-28' },
  { category: 'Text & Code', name: 'Markdown to HTML', description: 'Convert Markdown to valid HTML — browser-based, instant', route: '/markdown-to-html', lastmod: '2026-05-28' },
  { category: 'Text & Code', name: 'HTML to JSX', description: 'Convert HTML to React JSX — class→className, events, styles', route: '/html-to-jsx', lastmod: '2026-06-11' },
  { category: 'Text & Code', name: 'JSX to HTML', description: 'Convert React JSX to standard HTML — browser-based, instant', route: '/jsx-to-html', lastmod: '2026-06-11' },
  { category: 'Text & Code', name: 'HTML to TSX', description: 'Convert HTML to a TypeScript React component (TSX) — class→className, styles, interface Props scaffold', route: '/html-to-tsx', lastmod: '2026-06-26' },
  { category: 'Text & Code', name: 'TSX to HTML', description: 'Convert TSX to standard HTML — strips TypeScript types, interfaces, and JSX attributes', route: '/tsx-to-html', lastmod: '2026-06-26' },
  { category: 'Text & Code', name: 'JSON to CSV', description: 'Convert JSON array to CSV — comma, semicolon or tab delimiter', route: '/json-to-csv', lastmod: '2026-05-09' },
  { category: 'Text & Code', name: 'CSV to JSON', description: 'Convert CSV to JSON array — supports any delimiter, instant', route: '/csv-to-json', lastmod: '2026-05-28' },
  { category: 'Text & Code', name: 'XML to JSON', description: 'Convert XML to formatted JSON — browser-based, instant', route: '/xml-to-json', lastmod: '2026-05-28' },
  { category: 'Text & Code', name: 'JSON to XML', description: 'Convert JSON to valid XML document — browser-based, instant', route: '/json-to-xml', lastmod: '2026-06-11' },
  { category: 'Text & Code', name: 'YAML to JSON', description: 'Convert YAML to formatted JSON — browser-based, instant', route: '/yaml-to-json', lastmod: '2026-05-09' },
  { category: 'Text & Code', name: 'JSON to YAML', description: 'Convert JSON to clean YAML — browser-based, instant', route: '/json-to-yaml', lastmod: '2026-05-09' },
  { category: 'Text & Code', name: 'Base64 Encode', description: 'Encode text to Base64 — supports Unicode, browser-based', route: '/base64-encode', lastmod: '2026-05-09' },
  { category: 'Text & Code', name: 'Base64 Decode', description: 'Decode Base64 to plain text — supports Unicode, browser-based', route: '/base64-decode', lastmod: '2026-05-09' },
  { category: 'SEO', name: 'Meta tag generator', description: 'Generate SEO meta tags with live preview', route: '/meta-tags-generator', lastmod: '2026-05-28' },
  { category: 'SEO', name: 'OG Image Generator', description: 'Crop and export Open Graph images at 1200×630', route: '/og-image-generator', lastmod: '2026-05-04' },
  { category: 'SEO', name: 'Product Schema Generator', description: 'Generate Product schema markup (JSON-LD) for price, ratings, availability, shipping and returns', route: '/product-schema-generator', lastmod: '2026-05-28' },
  { category: 'SEO', name: 'Article Schema Generator', description: 'Generate Article schema markup (JSON-LD) for Google News, Discover and Search', route: '/article-schema-generator', lastmod: '2026-05-07' },
  { category: 'SEO', name: 'FAQ Schema Generator', description: 'Generate FAQPage schema markup (JSON-LD) for expandable Q&A in Google Search results', route: '/faq-schema-generator', lastmod: '2026-05-07' },
  { category: 'SEO', name: 'Organization Schema Generator', description: 'Generate Organization schema markup (JSON-LD) for Google Knowledge Panel and E-E-A-T', route: '/organization-schema-generator', lastmod: '2026-05-07' },
  { category: 'SEO', name: 'Local Business Schema Generator', description: 'Generate LocalBusiness schema markup (JSON-LD) for map cards, business hours and phone', route: '/local-business-schema-generator', lastmod: '2026-05-07' },
  { category: 'SEO', name: 'Breadcrumb Schema Generator', description: 'Generate BreadcrumbList schema markup (JSON-LD) for site path trails in Google SERP', route: '/breadcrumb-schema-generator', lastmod: '2026-05-07' },
  { category: 'AI', name: 'Lora', description: 'Lora — AI assistant for JSON-LD schema markup and SEO. Generate Product, Article, FAQ, BreadcrumbList structured data from plain English. Free plan: 100K tokens/month.', route: '/ai', lastmod: '2026-06-24', priority: '0.9' },
  { category: 'Images', name: 'WebP converter', description: 'Convert any image to WebP format', route: '/webp-converter', lastmod: '2026-05-28' },
  { category: 'Images', name: 'Favicon generator', description: 'Generate favicons from text, emoji, or image', route: '/favicon-generator', lastmod: '2026-04-25' },
  { category: 'Images', name: 'Compress JPG', description: 'Reduce JPEG file size with quality control', route: '/compress-jpg', lastmod: '2026-04-28' },
  { category: 'Images', name: 'Compress PNG', description: 'Lossless PNG compression, strip metadata', route: '/compress-png', lastmod: '2026-04-28' },
  { category: 'Images', name: 'Compress WebP', description: 'Reduce WebP file size, adjustable quality', route: '/compress-webp', lastmod: '2026-04-28' },
  { category: 'Images', name: 'PNG to JPG', description: 'Convert PNG images to JPG', route: '/png-to-jpg', lastmod: '2026-05-01' },
  { category: 'Images', name: 'JPG to PNG', description: 'Convert JPG images to PNG', route: '/jpg-to-png', lastmod: '2026-05-01' },
  { category: 'Images', name: 'WebP to JPG', description: 'Convert WebP images to JPG', route: '/webp-to-jpg', lastmod: '2026-05-01' },
  { category: 'Images', name: 'WebP to PNG', description: 'Convert WebP images to PNG', route: '/webp-to-png', lastmod: '2026-05-01' },
  { category: 'Images', name: 'PNG to WebP', description: 'Convert PNG images to WebP', route: '/png-to-webp', lastmod: '2026-05-01' },
  { category: 'Images', name: 'JPG to WebP', description: 'Convert JPG images to WebP', route: '/jpg-to-webp', lastmod: '2026-05-01' },
  { category: 'Images', name: 'JPEG to PNG', description: 'Convert JPEG images to PNG', route: '/jpeg-to-png', lastmod: '2026-05-01' },
  { category: 'Images', name: 'JPEG to WebP', description: 'Convert JPEG images to WebP', route: '/jpeg-to-webp', lastmod: '2026-05-01' },
  { category: 'Images', name: 'GIF to JPG', description: 'Convert GIF images to JPG', route: '/gif-to-jpg', lastmod: '2026-05-01' },
  { category: 'Images', name: 'GIF to PNG', description: 'Convert GIF images to PNG', route: '/gif-to-png', lastmod: '2026-05-01' },
  { category: 'Images', name: 'GIF to WebP', description: 'Convert GIF images to WebP', route: '/gif-to-webp', lastmod: '2026-05-01' },
  { category: 'Images', name: 'BMP to JPG', description: 'Convert BMP images to JPG', route: '/bmp-to-jpg', lastmod: '2026-05-01' },
  { category: 'Images', name: 'BMP to PNG', description: 'Convert BMP images to PNG', route: '/bmp-to-png', lastmod: '2026-05-01' },
  { category: 'Images', name: 'BMP to WebP', description: 'Convert BMP images to WebP', route: '/bmp-to-webp', lastmod: '2026-05-01' },
  { category: 'Images', name: 'AVIF to JPG', description: 'Convert AVIF images to JPG', route: '/avif-to-jpg', lastmod: '2026-05-01' },
  { category: 'Images', name: 'AVIF to PNG', description: 'Convert AVIF images to PNG', route: '/avif-to-png', lastmod: '2026-05-01' },
  { category: 'Images', name: 'AVIF to WebP', description: 'Convert AVIF images to WebP', route: '/avif-to-webp', lastmod: '2026-05-01' },
  { category: 'Images', name: 'TIFF to JPG', description: 'Convert TIFF images to JPG', route: '/tiff-to-jpg', lastmod: '2026-05-01' },
  { category: 'Images', name: 'TIFF to PNG', description: 'Convert TIFF images to PNG', route: '/tiff-to-png', lastmod: '2026-05-01' },
  { category: 'Images', name: 'TIFF to WebP', description: 'Convert TIFF images to WebP', route: '/tiff-to-webp', lastmod: '2026-05-01' },
  { category: 'Images', name: 'HEIC to JPG', description: 'Convert iPhone HEIC photos to JPG — no upload', route: '/heic-to-jpg', lastmod: '2026-05-18' },
  { category: 'Images', name: 'HEIC to WebP', description: 'Convert iPhone HEIC photos to WebP — no upload', route: '/heic-to-webp', lastmod: '2026-05-18' },
  { category: 'Utilities', name: 'QR Code Generator', description: 'Generate a QR code for any link with custom colours, a logo and PNG or SVG export', route: '/qr-code-generator', lastmod: '2026-08-12' },
  { category: 'Utilities', name: 'Text to QR Code Generator', description: 'Turn plain text into a QR code that displays instantly on scan — no link, no internet needed', route: '/text-to-qr-code-generator', lastmod: '2026-08-12' },
  { category: 'Utilities', name: 'WiFi QR Code Generator', description: 'Create a WiFi QR code guests scan to join — handles WPA3, hidden networks and special characters', route: '/wifi-qr-code-generator', lastmod: '2026-08-12' },
  { category: 'Utilities', name: 'vCard QR Code Generator', description: 'Generate a contact QR code that saves name, phone, email and company straight to any phone', route: '/vcard-qr-code-generator', lastmod: '2026-08-12' },
]
