export const TOOLS = [
  { category: 'SEO',    name: 'Meta tag generator',  description: 'Generate SEO meta tags with live preview',            route: '/meta-tags-generator', lastmod: '2026-04-28' },
  { category: 'SEO',    name: 'OG Image Generator',  description: 'Crop and export Open Graph images at 1200×630',       route: '/og-image-generator',  lastmod: '2026-05-04' },
  { category: 'Images', name: 'WebP converter',      description: 'Convert any image to WebP format',                    route: '/webp-converter',      lastmod: '2026-04-25' },
  { category: 'Images', name: 'Favicon generator',   description: 'Generate favicons from text, emoji, or image',        route: '/favicon-generator',   lastmod: '2026-04-25' },
  { category: 'Images', name: 'Compress JPG',        description: 'Reduce JPEG file size with quality control',          route: '/compress-jpg',        lastmod: '2026-04-28' },
  { category: 'Images', name: 'Compress PNG',        description: 'Lossless PNG compression, strip metadata',            route: '/compress-png',        lastmod: '2026-04-28' },
  { category: 'Images', name: 'Compress WebP',       description: 'Reduce WebP file size, adjustable quality',           route: '/compress-webp',       lastmod: '2026-04-28' },
  { category: 'Images', name: 'PNG to JPG',          description: 'Convert PNG images to JPG',                           route: '/png-to-jpg',          lastmod: '2026-05-01' },
  { category: 'Images', name: 'JPG to PNG',          description: 'Convert JPG images to PNG',                           route: '/jpg-to-png',          lastmod: '2026-05-01' },
  { category: 'Images', name: 'WebP to JPG',         description: 'Convert WebP images to JPG',                          route: '/webp-to-jpg',         lastmod: '2026-05-01' },
  { category: 'Images', name: 'WebP to PNG',         description: 'Convert WebP images to PNG',                          route: '/webp-to-png',         lastmod: '2026-05-01' },
  { category: 'Images', name: 'PNG to WebP',         description: 'Convert PNG images to WebP',                          route: '/png-to-webp',         lastmod: '2026-05-01' },
  { category: 'Images', name: 'JPG to WebP',         description: 'Convert JPG images to WebP',                          route: '/jpg-to-webp',         lastmod: '2026-05-01' },
  { category: 'Images', name: 'JPEG to PNG',         description: 'Convert JPEG images to PNG',                          route: '/jpeg-to-png',         lastmod: '2026-05-01' },
  { category: 'Images', name: 'JPEG to WebP',        description: 'Convert JPEG images to WebP',                         route: '/jpeg-to-webp',        lastmod: '2026-05-01' },
  { category: 'Images', name: 'GIF to JPG',          description: 'Convert GIF images to JPG',                           route: '/gif-to-jpg',          lastmod: '2026-05-01' },
  { category: 'Images', name: 'GIF to PNG',          description: 'Convert GIF images to PNG',                           route: '/gif-to-png',          lastmod: '2026-05-01' },
  { category: 'Images', name: 'GIF to WebP',         description: 'Convert GIF images to WebP',                          route: '/gif-to-webp',         lastmod: '2026-05-01' },
  { category: 'Images', name: 'BMP to JPG',          description: 'Convert BMP images to JPG',                           route: '/bmp-to-jpg',          lastmod: '2026-05-01' },
  { category: 'Images', name: 'BMP to PNG',          description: 'Convert BMP images to PNG',                           route: '/bmp-to-png',          lastmod: '2026-05-01' },
  { category: 'Images', name: 'BMP to WebP',         description: 'Convert BMP images to WebP',                          route: '/bmp-to-webp',         lastmod: '2026-05-01' },
  { category: 'Images', name: 'AVIF to JPG',         description: 'Convert AVIF images to JPG',                          route: '/avif-to-jpg',         lastmod: '2026-05-01' },
  { category: 'Images', name: 'AVIF to PNG',         description: 'Convert AVIF images to PNG',                          route: '/avif-to-png',         lastmod: '2026-05-01' },
  { category: 'Images', name: 'AVIF to WebP',        description: 'Convert AVIF images to WebP',                         route: '/avif-to-webp',        lastmod: '2026-05-01' },
  { category: 'Images', name: 'TIFF to JPG',         description: 'Convert TIFF images to JPG',                          route: '/tiff-to-jpg',         lastmod: '2026-05-01' },
  { category: 'Images', name: 'TIFF to PNG',         description: 'Convert TIFF images to PNG',                          route: '/tiff-to-png',         lastmod: '2026-05-01' },
  { category: 'Images', name: 'TIFF to WebP',        description: 'Convert TIFF images to WebP',                         route: '/tiff-to-webp',        lastmod: '2026-05-01' },
]
